version: "3.7"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    rertart: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    external: false